# api/src/main/resources/application.properties

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/usersModular
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# 'update' intentará actualizar el esquema existente.
# Para la primera vez, puedes usar 'create' o 'create-drop' (este último borra y crea la base de datos en cada inicio).
# Una vez que tu esquema esté estable, considera usar 'validate' o 'none' en entornos de producción.

# Opcional: Mostrar las consultas SQL en la consola (útil para depuración)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true